version: "3.9"

services:
  backend:
    build: .
    container_name: pdf-qna-backend

    ports:
      - "8000:8000"

    volumes:
      - .:/workspace

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg17

    container_name: pdf-qna-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_study_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
